a = input('Digite algo: ')
print(type(a))
print('É alfanumérico? ', a.isalnum())
print('É alfabético? ', a.isalpha())
print('Faz parte do ASCII? ', a.isascii())
print('É um digíto? ', a.isdigit())
print('Está em minúsculo? ', a.islower())
print('É um decimal? ', a.isdecimal())
print('É um identificador? ', a.isidentifier())
print('É possível imprimir na tela? ', a.isprintable())
print('É numérico? ', a.isnumeric())
print('É um espaço em branco? ', a.isspace())
print('É uma string do tipo title-cased? ', a.istitle())
print('É composta apenas de maiúsculas? ', a.isupper())
